### ISSUE TITLE
What if there are hundreds of thousands of vxa files per generation?

### ISSUE THREAD

**Issue by liusida** [liusida/gpuVoxels#1]
Then it will become a little time consuming to generate all 100000 files.

Here is an idea: use a common vxa files as base, only generate the differences in each vxa files. So the program read the base first and overwrite the part stated in a specific vxa.

Maybe there should be another filename extension for the file only contains difference. VXD? Because then others won't try to import the incomplete file to VoxCAD.

**Comment by skriegman** [comment]
There won't be this many files, we will probably use 100-1000 individuals per generation, but I like your idea. Also when using a large workspace (many voxels aka cubes), the individual files can be huge and take a long time to read and write and copy.

**Comment by liusida** [comment]
solved.
