### ISSUE TITLE
Compatibility with Voxelyze

### ISSUE THREAD

**Issue by nhatminh2h** [liusida/gpuVoxels#20]
Hi,

Does the new .vxa file have the same formatting as the one the original Voxelyze engine used? I have skimmed through and they look similar but I just wanted to confirm.

Many Thanks,
Minh Vu

**Comment by davidmatthews1uvm** [comment]
Hi Minh Vu,

This project is now being developed as voxcraft-sim.
https://github.com/voxcraft/voxcraft-sim

In general the two VXA formats are similar but not identical. We have some documentation on the differences but it is not complete so if you have trouble finding things please feel free to submit an issue.
 
Best,
David
